apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: vscan-api
  name: vscan-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: vscan-api
    spec:
      containers:
      - args:
        - --aws.sqs.region=eu-west-2
        - --aws.sqs.access.key=$(AWS_SQS_KEY)
        - --aws.sqs.secret.key=$(AWS_SQS_SECRET)
        - --aws.s3.region=eu-west-2
        - --aws.s3.access.key=$(AWS_S3_KEY)
        - --aws.s3.secret.key=$(AWS_S3_SECRET)
        - --clamav.host=$(CLAM_AV_SERVICE_HOST)
        - --clamav.port=$(CLAM_AV_SERVICE_PORT)
        - --egar.vscan.req.queue=develop_vscan_request
        - --egar-vscan.res.queue=develop_vscan_reponse
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: dbuser
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: dbpass
          - name: AWS_S3_KEY
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: awss3ackey
          - name: AWS_S3_SECRET
            valueFrom:
              secretKeyRef:
                name: egar-secret
                key: awss3seckey
        image: pipe.egarteam.co.uk/egar-vscan-api:$VSCAN_API_VER
        name: vscan-api
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 20
          httpGet:
            path: /healthz
            port: 8080
        resources: {}
      restartPolicy: Always
status: {}
